### ISSUE TITLE
Version 2 missing from npm

### ISSUE THREAD

**Issue by EgidioCaprino** [Flolagale/mailin#119] opened 2017-01-03 13:01 UTC
The doc says to install version 2 for older node, but it is not present in npm:

``` bash
$ npm show mailin@* version
mailin@0.0.0 '0.0.0'
mailin@0.0.1 '0.0.1'
mailin@0.0.2 '0.0.2'
mailin@0.0.3 '0.0.3'
mailin@0.0.4 '0.0.4'
mailin@0.0.5 '0.0.5'
mailin@0.0.6 '0.0.6'
mailin@0.0.7 '0.0.7'
mailin@0.0.8 '0.0.8'
mailin@0.0.9 '0.0.9'
mailin@0.0.10 '0.0.10'
mailin@0.0.11 '0.0.11'
mailin@0.0.12 '0.0.12'
mailin@0.0.13 '0.0.13'
mailin@0.1.0 '0.1.0'
mailin@0.1.1 '0.1.1'
mailin@0.1.2 '0.1.2'
mailin@0.1.3 '0.1.3'
mailin@1.0.0 '1.0.0'
mailin@1.0.1 '1.0.1'
mailin@3.0.0 '3.0.0'
mailin@3.0.1 '3.0.1'
mailin@3.0.2 '3.0.2'
mailin@3.0.3 '3.0.3'
```

**Comment by dweremeichik** [comment] 2017-05-22 03:44
Duplicate of #105

**Closed** 2019-01-31 15:08 UTC
